"""3D model builder — constructs geometry from analyzed drawing data.

Supports three output formats:
  - **GLB** (binary glTF 2.0) — requires ``trimesh``; most compatible
  - **OBJ** (Wavefront) — no extra dependencies; works everywhere
  - **STL** (ASCII) — no extra dependencies; great for 3D printing

The builder always falls back gracefully: GLB → OBJ when trimesh is
absent, keeping the program fully functional without optional deps.
"""

from __future__ import annotations

import json
import logging
import struct
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ─── Geometry helpers ─────────────────────────────────────────────────────────


def _box(
    x: float, y: float, z: float,
    w: float, d: float, h: float,
) -> Tuple[List[Tuple], List[Tuple]]:
    """Return (vertices, triangles) for an axis-aligned box.

    Coordinate system: X right, Y forward (into screen), Z up.
    """
    v = [
        (x,     y,     z),      # 0 bottom-front-left
        (x + w, y,     z),      # 1 bottom-front-right
        (x + w, y + d, z),      # 2 bottom-back-right
        (x,     y + d, z),      # 3 bottom-back-left
        (x,     y,     z + h),  # 4 top-front-left
        (x + w, y,     z + h),  # 5 top-front-right
        (x + w, y + d, z + h),  # 6 top-back-right
        (x,     y + d, z + h),  # 7 top-back-left
    ]
    f = [
        (0, 2, 1), (0, 3, 2),   # bottom
        (4, 5, 6), (4, 6, 7),   # top
        (0, 1, 5), (0, 5, 4),   # front
        (2, 3, 7), (2, 7, 6),   # back
        (3, 0, 4), (3, 4, 7),   # left
        (1, 2, 6), (1, 6, 5),   # right
    ]
    return v, f


def _geometry_to_mesh(data: Dict) -> Tuple[List[Tuple], List[Tuple]]:
    """Convert a geometry dict to a flat (vertices, triangles) pair.

    Handles both room-based and overall-dimensions layouts.
    """
    rooms: List[Dict] = data.get("rooms", [])
    default_h = float(data.get("floor_height", 2.8))

    if not rooms:
        ow = float(
            data.get("overall_width")
            or data.get("overall_dimensions", {}).get("width", 5.0)
        )
        od = float(
            data.get("overall_depth")
            or data.get("overall_dimensions", {}).get("depth", 5.0)
        )
        oh = float(
            data.get("overall_height")
            or data.get("overall_dimensions", {}).get("height", default_h)
        )
        rooms = [{"name": "body", "x": 0.0, "y": 0.0, "width": ow, "depth": od, "height": oh}]

    all_verts: List[Tuple] = []
    all_tris: List[Tuple] = []

    for room in rooms:
        rx = float(room.get("x", 0))
        ry = float(room.get("y", 0))
        rw = float(room.get("width", 1))
        rd = float(room.get("depth", 1))
        rh = float(room.get("height", default_h))
        base = len(all_verts)
        verts, tris = _box(rx, ry, 0.0, rw, rd, rh)
        all_verts.extend(verts)
        all_tris.extend((t[0] + base, t[1] + base, t[2] + base) for t in tris)

    return all_verts, all_tris


def _cross(a: Tuple, b: Tuple) -> Tuple[float, float, float]:
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _sub(a: Tuple, b: Tuple) -> Tuple[float, float, float]:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


# ─── OBJ writer ───────────────────────────────────────────────────────────────


def write_obj(data: Dict, output_path: str) -> str:
    """Write a Wavefront OBJ file from geometry data.

    OBJ convention uses Y-up; we swap our Z-up coords accordingly.
    """
    verts, tris = _geometry_to_mesh(data)

    with open(output_path, "w") as fh:
        fh.write("# Generated by design_to_3d (OpenJarvis)\n\n")
        for v in verts:
            # Convert: X→X, Y(forward)→-Z, Z(up)→Y
            fh.write(f"v {v[0]:.4f} {v[2]:.4f} {-v[1]:.4f}\n")
        fh.write("\n")
        for t in tris:
            fh.write(f"f {t[0]+1} {t[1]+1} {t[2]+1}\n")

    return output_path


# ─── STL writer ───────────────────────────────────────────────────────────────


def write_stl(data: Dict, output_path: str) -> str:
    """Write an ASCII STL file from geometry data."""
    verts, tris = _geometry_to_mesh(data)

    with open(output_path, "w") as fh:
        fh.write("solid design_to_3d\n")
        for t in tris:
            v0, v1, v2 = verts[t[0]], verts[t[1]], verts[t[2]]
            e1 = _sub(v1, v0)
            e2 = _sub(v2, v0)
            nx, ny, nz = _cross(e1, e2)
            # Apply same coord swap as OBJ
            fh.write(f"  facet normal {nx:.6f} {nz:.6f} {-ny:.6f}\n")
            fh.write("    outer loop\n")
            for vi in (t[0], t[1], t[2]):
                v = verts[vi]
                fh.write(f"      vertex {v[0]:.6f} {v[2]:.6f} {-v[1]:.6f}\n")
            fh.write("    endloop\n")
            fh.write("  endfacet\n")
        fh.write("endsolid design_to_3d\n")

    return output_path


# ─── GLB writer (trimesh) ─────────────────────────────────────────────────────


def write_glb(data: Dict, output_path: str) -> str:
    """Write a binary glTF (GLB) file using trimesh.

    Falls back to OBJ (with .obj extension) when trimesh is not installed.
    """
    try:
        import numpy as np
        import trimesh
    except ImportError:
        logger.warning("trimesh not found; falling back to OBJ output")
        obj_path = str(Path(output_path).with_suffix(".obj"))
        return write_obj(data, obj_path)

    verts, tris = _geometry_to_mesh(data)
    v_arr = np.array(verts, dtype=np.float32)
    f_arr = np.array(tris, dtype=np.uint32)

    # Convert to glTF coordinate system (Y-up, right-handed: swap Y/Z)
    v_gltf = np.column_stack([v_arr[:, 0], v_arr[:, 2], -v_arr[:, 1]])

    mesh = trimesh.Trimesh(vertices=v_gltf, faces=f_arr, process=False)
    mesh.export(output_path, file_type="glb")
    return output_path


# ─── Public API ───────────────────────────────────────────────────────────────


def build_model(
    geometry: Dict[str, Any],
    output_path: Optional[str] = None,
    fmt: str = "glb",
) -> str:
    """Build a 3D model file from structured geometry data.

    Parameters
    ----------
    geometry:
        Geometry dict returned by :func:`analyzer.analyze_drawing` or a
        synthesized dict combining multiple analyses.
    output_path:
        Destination file path. If omitted, a temp file is created.
        The file extension overrides *fmt* when present.
    fmt:
        Default format: ``'glb'`` (requires trimesh), ``'obj'``, or ``'stl'``.

    Returns
    -------
    str
        Absolute path to the written model file.
    """
    if not output_path:
        ext = {"glb": ".glb", "obj": ".obj", "stl": ".stl"}.get(fmt.lower(), ".glb")
        output_path = str(Path(tempfile.gettempdir()) / f"design_to_3d_model{ext}")

    # Extension overrides format
    ext_from_path = Path(output_path).suffix.lower().lstrip(".")
    if ext_from_path in ("glb", "obj", "stl"):
        fmt = ext_from_path

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    fmt = fmt.lower()
    if fmt == "glb":
        return write_glb(geometry, output_path)
    elif fmt == "stl":
        return write_stl(geometry, output_path)
    else:
        return write_obj(geometry, output_path)


def merge_geometries(analyses: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Merge multiple drawing analyses into a single geometry dict.

    When a floor plan is present it anchors the layout; elevations
    contribute height information. Technical/isometric drawings are used
    for overall dimensions when no floor plan exists.
    """
    if not analyses:
        return {}

    if len(analyses) == 1:
        return analyses[0]

    # Prefer floor_plan as the primary geometry source
    floor_plan = next((a for a in analyses if a.get("drawing_type") == "floor_plan"), None)
    elevations = [a for a in analyses if a.get("drawing_type") == "elevation"]

    if floor_plan:
        merged = dict(floor_plan)
        # Apply height from front elevation if available
        front_elev = next((e for e in elevations if e.get("direction") == "front"), None)
        if front_elev:
            merged["floor_height"] = float(front_elev.get("floor_height", merged.get("floor_height", 2.8)))
        return merged

    # No floor plan — aggregate into a synthetic bounding box
    widths = [float(a.get("overall_width") or a.get("overall_dimensions", {}).get("width", 5)) for a in analyses]
    depths = [float(a.get("overall_depth") or a.get("overall_dimensions", {}).get("depth", 5)) for a in analyses]
    heights = [float(a.get("total_height") or a.get("floor_height") or a.get("overall_dimensions", {}).get("height", 3)) for a in analyses]

    return {
        "drawing_type": "merged",
        "overall_width": max(widths),
        "overall_depth": max(depths),
        "floor_height": max(heights),
        "rooms": [],
    }
